apiVersion: v1
kind: Service
metadata:
  name: hellofromnode
  labels:
    app: hellofromnode
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 31118
  selector:
    app: hellofromnode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellofromnode
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hellofromnode
  template:
    metadata:
      labels:
        app: hellofromnode
    spec:
      containers:
      - name: hellofromnode
        image: asalilje/hellofromnode:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
      - name: pi-blinkt
        image: asalilje/pi-blinkt:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3200
          protocol: TCP
        volumeMounts:
        - mountPath: /sys
          name: sys-tree
      volumes:
      - name: sys-tree
        hostPath:
          path: /sys
